services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: museguide-postgres
    environment:
      POSTGRES_DB: museguide
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - museguide-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: museguide-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/museguide
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - museguide-network
  # Next.js Frontend (опционально)


volumes:
  postgres_data:

networks:
  museguide-network:
    driver: bridge
